#!/bin/bash
packages=(shared "$1")

for p in "${packages[@]}"; do stow --delete "$p"; done
git pull origin master
for p in "${packages[@]}"; do stow "$p"; done

if command -v systemctl > /dev/null 2>&1; then
  systemctl --user daemon-reload
fi
